# Site settings
author: Sierra Wallace
title: 
header-img: img/home-bg.png
email: sskwallace@gmail.com
copyright_name: Sierra Wallace
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sierraskyewallace

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
